constant_prob:
  p: 0.5
  allow_self_connections: false

distance_based:
  sigma: 0.75
  max_prob: 0.5

prob_based_block:
  num_modules: 4
  within_module_connection_prob: 0.1
  between_module_connection_prob: 0.01
  allow_self_connections: true

optional_connect:
  src_ID: 1
  tgt_ID: 0