
constant_prob:
  num_modules: 4
  e_rate: 0.75
  p_in: 0.1
  p_out: 0.05

distance_based:
  sigma: 0.75
  max_prob: 0.5

prob_based_block:
  num_modules: 4
  within_module_connection_prob: 0.1
  between_module_connection_prob: 0.01
  allow_self_connections: true
