pqn_test:
    input: 0.15         # [nA]
    input_type: "step"  # (step or continuous)
    duration: 2000.0    # [ms]
    graph_name: "PQN_V_test"
    
spatial_recognition:
  duration: 10000.0
  input:
    type: "spatial"
    strength: 0.5
    duration_stim: 0.1
    input_nodes: 30
  output:
    teaching_duration: 2.5
    readout_nodes: 60
  experiment:
    n_train: 20
    n_test: 10

voice_recognition:
  name: "voice_recognition"
  input:
    type: "cochleagram"
    input_dt: 0.008        # 旧 INPUT_DT_COCH
    input_nodes: 17
  output:
    teaching_duration: 2.5
    readout_nodes: 60
  experiment:
    duration_interval: 10.0 # 旧 DURATION_INTERVAL_COCH
    n_train: 14  
    n_test: 6

spatio_temporal:
  name: "spatio_temporal"
  input:
    type: "spatio_temp"
    strength: 0.5
    duration_stim: 0.1
    input_dt: 0.01         # 旧 SPATIO_TEMP_DT
    input_nodes: 30
  output:
    teaching_duration: 2.5
    readout_nodes: 60
  experiment:
    duration_interval: 10.0
    n_train: 20
    n_test: 10

real_time_control:
  name: "real_time_control"
  input:
    type: "real_time"
    strength: 0.5
    duration_stim: 0.1
    input_dt: 0.01   
  output:
    teaching_duration: 2.5
    readout_nodes: 60
  experiment:
    duration_interval: 10.0
    n_train: 20
    n_test: 10  
  realtime:
    io_interval: 0.005 # 5ms周期