simulation:
  N: 150
  dt: 0.1             # 時間ステップ (ms)
  seed: null         # 乱数シード

inputs:
  GaussianNoise:
    enable: false
    mean: 10.0      # [nA] 
    sd: 1.0        # [nA]

neurons:
  Layer_Exc:
    type: LIF
    mode: excitatory
    num: 2
  # Layer_Inh:
  #   type: LIF
  #   mode: inhibitory
  #   num: 1

synapses:
  from_Exc:
    source: Layer_Exc
    plasticity: 
      type: StaticPulse
      mode: default
    synapse:
      type: ExpCurr
      mode: excitatory
  # from_Inh:
  #   source: Layer_Inh
  #   plasticity: 
  #     type: StaticPulse
  #     mode: default
  #   synapse:
  #     type: ExpCurr
  #     mode: inhibitory

network:
  space: block_2d
  connection: optional_connect
  weight: constant
  delay: constant 
