simulation:
  N: 150
  dt: 0.1             # 時間ステップ (ms)
  duration: 2000     # シミュレーション時間 (s)
  backend: "CUDA"     # 実行バックエンド

neurons:
  Layer_Exc:
    type: "PQN_int"
    mode: "RSexci"
    num: 100
  Layer_Inh:
    type: "PQN_int"
    mode: "RSinhi"
    num: 50

network:
  space: "grid_3d"
  connection: "constant_prob"
  weight: "constant"
  delay: "constant"

synapse_groups:
  Exc_to_Inh:
    source: "Layer_Exc"
    target: "Layer_Inh"
    synapse: "tsodyks_facilitate"
    plasticity: "static"
    weight_scale: 1.0
  Inh_to_Exc:
    source: "Layer_Inh"
    target: "Layer_Exc"
    synapse: "tsodyks_depress"
    plasticity: "static"
    weight_scale: -4.0

data: pqn_test
